name: ma_iscanner_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+4
  logger: ^1.1.0
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.5+3
  tflite_flutter: ^0.11.0
  image: ^3.3.0
  collection: ^1.15.0 
  permission_handler: ^11.3.1
  #gallery_saver: ^2.3.2
  #image_gallery_saver: ^ 2.0.3
  file_saver: ^0.2.14
  flutter_colorpicker: ^1.0.3
  #audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  fonts:
    - family: KantumruyPro-Bold
      fonts:
        - asset: assets/font/KantumruyPro-Bold.ttf
    - family: KantumruyPro-Regular
      fonts:
        - asset: assets/font/KantumruyPro-Regular.ttf
    - family: KantumruyPro-MediumItalic
      fonts:
        - asset: assets/font/KantumruyPro-MediumItalic.ttf
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/corn.tflite
    - assets/labels.txt
    - assets/MaiscannerLogo.png
    - assets/plant_tips.png
    #Recommendation tips as image englis and tagalog
    - assets/images/


    
  
